### ISSUE TITLE
Feature request: fully styleable notification box

### ISSUE THREAD

**Issue by nstohler** [alexcrack/angular-ui-notification#53]
We use the component to display real time information notifications that don't really act as warning/info/error/... pop-ups. We had to change the CSS a bit to get the right colors and styling of the overall component, since we could not use the predefined icons and wanted to put some font awesome icons insted. An option to provide a custom template for the whole notification box would be great!

**Comment by AoDev** [comment]
@nstohler There is a templateUrl option. Isn't it what you are looking for?

**Comment by nstohler** [comment]
I tried using it, but it doesn't pick up my template:
http://plnkr.co/edit/Fpxw7BRdbbQLqdnOYr22?p=preview

**Comment by alexcrack** [comment]
There is erro within you template

``` html
wusel
<div class="test">
    <h3 ng-show="title" ng-bind-html="title"></h3>
    <div class="message" ng-bind-html="message"></div>
</div>
```

wusel - is not a tag =)

I've fixed it and now it works!
http://plnkr.co/edit/G6U3G8nkvVHnnkxkHx97?p=preview

**Comment by nstohler** [comment]
Thanks!
Seems like I messed up my plunk!

So I try to get the pop up colored in some custom color by applying a css class while keeping the animation and everything else. But I still get a green top border. Any way to do this? 

http://plnkr.co/edit/YDydmoOIfRPeaG364ZAt?p=preview
(Error notification button, pop up should be fully black)

**Comment by alexcrack** [comment]
This is CSS problem. Not notification module.
Just use "!important" attribute on you background.
http://plnkr.co/edit/EMygpeHB2Y7U3FtkzvoB?p=preview

**Comment by nstohler** [comment]
Great! Thanks for all the help. I'm still new to web development, so not so sure what to check in what order (or what is possible and how)!

**Comment by AoDev** [comment]
@nstohler I'd recommend you to use the less file from the source. It's much easier to configure, especially if you use Bootstrap.
